export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS';
export const WEATHER_ERROR = 'WEATHER_ERROR';
export const FORECAST_REQUEST = 'FORECAST_REQUEST';
export const FORECAST_ERROR = 'FORECAST_ERROR';
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS';